
spring:
  application:
    name: spring-cloud-producer
  zipkin:
    base-url: http://localhost:7003
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9000

eureka:
#  instance:
#    hostname: peer1
  client:
    serviceUrl:
     defaultZone: http://localhost:8000/eureka/



