server:
  port: 7001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baoziface/spring-cloud-starter/     # 配置git仓库的地址
          search-paths: config-repo                         # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: guoqiang4321@163.com                                           # git仓库的账号
          password: 7466370gq                                            # git仓库的密码
